#!/bin/bash
###Scripts for setting up the environment
#Author: Shashank

apt-get update
apt-get upgrade
apt-get install wget
apt-get install python-pip
pip install django
pip install -r requirements.txt